### ISSUE TITLE
Action Hud fails for some Token

### ISSUE THREAD

**Issue by garvielloken42** [espositos/fvtt-tokenactionhud#236]
For some Tokens the Action Hud Fails after the Recent update
I have the follwoing error in the Dev Console.
![2021-05-30 14_32_28-Window](https://user-images.githubusercontent.com/85063620/120104267-ec8c5c00-c153-11eb-9fef-b1981015226b.png)
![2021-05-30 14_33_23-Window](https://user-images.githubusercontent.com/85063620/120104291-029a1c80-c154-11eb-83ee-32c86008aa66.png)

**Comment by TheTural** [comment]
It fails on tokens with spells as a result of the changes made yesterday relating to 0.8.x compatibility.

If you replace the `getData(i)` instances with `i.data` as it was before on lines 851 and 853, it'll fix it for the time being.

Lines 850-854:
```
        if (settings.get('showAllNonpreparableSpells')) {
            result = spells.filter(i => getData(i).preparation.prepared || nonpreparableSpells.includes(getData(i).preparation.mode) || getData(i).level === 0)
        } else {
            result = spells.filter(i => getData(i).preparation.prepared);
        }
```
Change to:
```
        if (settings.get('showAllNonpreparableSpells')) {
            result = spells.filter(i => i.data.preparation.prepared || nonpreparableSpells.includes(i.data.preparation.mode) || i.data.level === 0)
        } else {
            result = spells.filter(i => i.data.preparation.prepared);
        }
```

**Comment by ctbritt** [comment]
I made those changes and I'm still getting nothing but errors: 

```
Uncaught (in promise) TypeError: actor.effects.entries.some is not a function
    at dnd5e-actions.js:629
    at Array.forEach (<anonymous>)
    at ActionHandler5e._addConditionsSubcategory (dnd5e-actions.js:625)
    at ActionHandler5e._getConditionsList (dnd5e-actions.js:555)
    at ActionHandler5e.doBuildActionList (dnd5e-actions.js:35)
    at ActionHandler5e.buildActionList (actionHandler.js:32)
    at TokenActionHUD.updateHud (tokenactionhud.js:386)
```

**Comment by Battenhatch** [comment]
There are two errors - one for tokens with spells, and one if you enable conditions in the HUD

**Comment by ctbritt** [comment]
so there are. I turned off categories and non-preparable spells and it seems to work ok in 0.8.5, but now in 7.10, normal action items such a melee attack aren't showing up.

**Comment by ctbritt** [comment]
OK. I finagled some of the settings and got back working, after changing the code suggested by @TheTural above. Disabling "HIding actions longer than 1 round" brought inventory and feats tabs back.

**Comment by espositos** [comment]
So this should be fixed for both 0.7.x and 0.8.x, but please let me know if it's not
